// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA69GwMV58gmuorm-qs82FGZfh7LlTsIQg',
    appId: '1:154609337928:web:ef5c81da2cfc5dca18ba7d',
    messagingSenderId: '154609337928',
    projectId: 'dibs-67d1a',
    authDomain: 'dibs-67d1a.firebaseapp.com',
    storageBucket: 'dibs-67d1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT94j5K8efHjz18uDWwKWzU2YGIv3AWvg',
    appId: '1:154609337928:android:37c9d6a5ad5bcbfe18ba7d',
    messagingSenderId: '154609337928',
    projectId: 'dibs-67d1a',
    storageBucket: 'dibs-67d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvn5wSXrCMt02ywr6smdJj0s94Ny2Bbew',
    appId: '1:154609337928:ios:d2d59b13e3e7bcc618ba7d',
    messagingSenderId: '154609337928',
    projectId: 'dibs-67d1a',
    storageBucket: 'dibs-67d1a.appspot.com',
    iosBundleId: 'com.example.dibs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvn5wSXrCMt02ywr6smdJj0s94Ny2Bbew',
    appId: '1:154609337928:ios:d2d59b13e3e7bcc618ba7d',
    messagingSenderId: '154609337928',
    projectId: 'dibs-67d1a',
    storageBucket: 'dibs-67d1a.appspot.com',
    iosBundleId: 'com.example.dibs',
  );
}
